# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oplus/sm8350-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter martini OP524F RMX2202 RMX3312 RMX3360 RMX3461,$(TARGET_DEVICE)),)

endif
